# force mv, rm and cp to ask user before clobbering file
alias ll="ls -alFh"
alias mktar="tar -czvf $*"
alias sshclic="ssh -X amc2316@clic.cs.columbia.edu"
alias lstar="tar -tvf $*"
alias clipboard="pbcopy"
alias jump="ssh -Atq jump.adnxs.net"
alias ipaddr="ipconfig getifaddr en0"
alias jenkins="~/bin/jenkins"
alias idea="vim ~/.ideas.md"
alias learn="subl ~/learn.md"
alias today="echo $(date +%d-%b-%Y)"
alias taffy-mysql="mysql --i-am-a-dummy --prompt 'general-services> ' -uapp_test_frame_u -pPruw6Abr -h mysql-testing-framework-master.prod.adnxs.net testing_framework_usage"
alias taffy="~/ftf_nodev/bin/taffy"
