# force mv, rm and cp to ask user before clobbering file
alias ll="ls -alFh"
alias mktar="tar -czvf $*"
alias sshclic="ssh -X amc2316@clic.cs.columbia.edu"
alias lstar="tar -tvf $*"
alias clipboard="pbcopy"
alias jump="ssh -Atq jump.adnxs.net"
alias ipaddr="ipconfig getifaddr en0"
alias push="~/bin/push"
alias pull="~/bin/pull"
alias jenkins="~/bin/jenkins"
alias idea="vim ~/.ideas.md"
alias today="echo $(date +%d-%b-%Y)"
